
import { Country, LedgerItem } from '@/context/WealthContext';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Platform } from 'react-native';
import { CalculationResult, Heir } from './inheritance';

export async function exportLedgerToPDF(items: LedgerItem[], country: Country, netWorth: number) {
  const html = `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
        <style>
          body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #1e293b; }
          h1 { color: #065f46; font-size: 24px; margin-bottom: 8px; }
          h2 { color: #92400e; font-size: 18px; margin-top: 24px; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; }
          table { width: 100%; border-collapse: collapse; margin-top: 16px; }
          th { text-align: left; background-color: #f8fafc; padding: 12px; border-bottom: 2px solid #e2e8f0; font-size: 14px; }
          td { padding: 12px; border-bottom: 1px solid #e2e8f0; font-size: 14px; }
          .amount { text-align: right; font-weight: bold; }
          .summary { margin-top: 40px; padding: 20px; background-color: #065f46; color: white; border-radius: 8px; }
          .summary-row { display: flex; justify-content: space-between; margin-bottom: 8px; }
          .total { font-size: 20px; font-weight: bold; border-top: 1px solid rgba(255,255,255,0.2); pt: 8px; }
          .footer { margin-top: 60px; font-size: 10px; color: #64748b; text-align: center; }
        </style>
      </head>
      <body>
        <h1>ZAIZEN Financial Report</h1>
        <p>Region: ${country.name} | Date: ${new Date().toLocaleDateString()}</p>

        <h2>Assets</h2>
        <table>
          <thead>
            <tr><th>Category</th><th>Description</th><th class="amount">Amount</th></tr>
          </thead>
          <tbody>
            ${items.filter(i => i.type === 'asset').map(i => `
              <tr><td>${i.category}</td><td>${i.description}</td><td class="amount">${i.amount.toLocaleString('en-US')} ${country.currency}</td></tr>
            `).join('')}
          </tbody>
        </table>

        <h2>Debts & Credits</h2>
        <table>
          <thead>
            <tr><th>Type</th><th>Category</th><th class="amount">Amount</th></tr>
          </thead>
          <tbody>
            ${items.filter(i => i.type !== 'asset').map(i => `
              <tr><td>${i.type.toUpperCase()}</td><td>${i.category}</td><td class="amount">${i.type === 'debt' ? '-' : '+'}${i.amount.toLocaleString()} ${country.currency}</td></tr>
            `).join('')}
          </tbody>
        </table>

        <div class="summary">
          <div class="summary-row"><span>Total Assets:</span> <span>${items.filter(i => i.type === 'asset').reduce((a, b) => a + b.amount, 0).toLocaleString('en-US')} ${country.currency}</span></div>
          <div class="summary-row"><span>Total Debts:</span> <span>${items.filter(i => i.type === 'debt').reduce((a, b) => a + b.amount, 0).toLocaleString('en-US')} ${country.currency}</span></div>
          <div class="summary-row" class="total"><span>Net Worth:</span> <span>${netWorth.toLocaleString('en-US')} ${country.currency}</span></div>
        </div>

        <div class="footer">
          Generated by ZAIZEN - Secure & Shari'ah Compliant Estate Management
        </div>
      </body>
    </html>
  `;

  await printToFile(html, 'Zaizen_Financial_Report');
}

export async function exportInheritanceToPDF(result: CalculationResult, country: Country) {
  const html = `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
        <style>
          body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #1e293b; }
          h1 { color: #065f46; font-size: 24px; margin-bottom: 8px; }
          .card { border: 1px solid #e2e8f0; border-radius: 12px; padding: 24px; margin-bottom: 24px; }
          .header-val { font-size: 28px; font-weight: bold; color: #065f46; }
          table { width: 100%; border-collapse: collapse; margin-top: 24px; }
          th { text-align: left; padding: 12px; border-bottom: 2px solid #e2e8f0; }
          td { padding: 12px; border-bottom: 1px solid #e2e8f0; }
          .share { color: #64748b; font-size: 12px; }
          .footer { margin-top: 60px; font-size: 10px; color: #64748b; text-align: center; }
        </style>
      </head>
      <body>
        <h1>Islamic Inheritance Distribution</h1>
        <p>Prepared on: ${new Date().toLocaleDateString()}</p>

        <div class="card">
          <div style="font-size: 14px; color: #64748b;">Net Distributable Estate</div>
          <div class="header-val">${result.netDistributableEstate.toLocaleString('en-US')} ${country.currency}</div>
          <div style="margin-top: 12px; font-size: 12px;">
            Settled Debts: ${result.funeralAndDebts.toLocaleString('en-US')} ${country.currency}<br/>
            Wasiyyah (Bequests): ${result.wasiyyahAmount.toLocaleString('en-US')} ${country.currency}
          </div>
        </div>

        <h2>Heir Distributions (Fara'id)</h2>
        <table>
          <thead>
            <tr><th>Heir</th><th>Share %</th><th style="text-align: right;">Amount</th></tr>
          </thead>
          <tbody>
            ${result.distributions.map(d => `
              <tr>
                <td>
                  <strong>${d.heir.charAt(0).toUpperCase() + d.heir.slice(1)}</strong> (${d.count})
                  ${d.names && d.names.some(n => n.trim()) ? `<br/><span class="share">${d.names.filter(n => n.trim()).join(', ')}</span>` : ''}
                </td>
                <td class="share">${(d.share * 100).toFixed(2)}%</td>
                <td style="text-align: right; font-weight: bold;">${d.amount.toLocaleString('en-US')} ${country.currency}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>

        <div class="footer">
          Distribution calculated according to Islamic Inheritance Principles.<br/>
          Generated by ZAIZEN
        </div>
      </body>
    </html>
  `;

  await printToFile(html, 'Zaizen_Inheritance_Summary');
}

export async function exportConfirmationStatement(items: LedgerItem[], country: Country) {
  if (items.length === 0) return;

  const leadItem = items[0];
  const isDebt = leadItem.type === 'debt';
  const title = isDebt ? 'DEBT CONFIRMATION STATEMENT' : 'CREDIT CONFIRMATION STATEMENT';
  const subject = isDebt ? 'Confirmation of Outstanding Debt' : 'Confirmation of Outstanding Credit';
  const creatorName = "GHOUENZEN SOULEMANOU";
  const creatorEmail = "gsouleman@gmail.com";
  const creatorAddress = "Douala, Cameroon";
  const creatorTel = "675 29 98 68 / 697 11 11 59";

  const totalAmount = items.reduce((sum, item) => sum + item.amount, 0);

  const html = `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
        <style>
          body { font-family: 'Helvetica', Arial, sans-serif; padding: 40px; color: #333; line-height: 1.6; }
          .header-title { text-align: center; color: #065f46; font-size: 20px; font-weight: bold; border-bottom: 2px solid #065f46; padding-bottom: 10px; margin-bottom: 30px; text-transform: uppercase; }
          .date { text-align: right; margin-bottom: 20px; font-weight: bold; }
          .recipient { margin-bottom: 5px; font-weight: bold; }
          .subject { text-decoration: underline; font-weight: bold; margin-bottom: 25px; }
          .greeting { margin-bottom: 15px; }
          .main-text { margin-bottom: 25px; text-align: justify; }
          .details-title { font-weight: bold; margin-bottom: 10px; }
          table { width: 100%; border-collapse: collapse; margin-bottom: 20px; background-color: #fdfaf4; }
          th { background-color: #f3ece0; padding: 12px; border: 1px solid #ddd; text-align: left; font-size: 14px; }
          td { padding: 12px; border: 1px solid #ddd; font-size: 14px; vertical-align: top; }
          .total-row { background-color: #f3ece0; font-weight: bold; }
          .amount-box { border: 2px solid #BA9411; background-color: #fdfaf4; border-radius: 8px; padding: 20px; margin: 30px 0; border-left-width: 8px; }
          .amount-large { font-size: 22px; font-weight: bold; color: #065f46; margin-bottom: 5px; }
          .confirmation-box { border: 1px dashed #BA9411; border-radius: 12px; padding: 20px; margin-top: 40px; background-color: #fdfaf4; }
          .confirmation-title { color: #065f46; font-weight: bold; font-size: 14px; margin-bottom: 15px; text-transform: uppercase; }
          .checkbox-item { display: flex; align-items: flex-start; margin-bottom: 12px; font-size: 13px; }
          .checkbox { width: 16px; height: 16px; border: 1px solid #333; margin-right: 10px; flex-shrink: 0; margin-top: 2px; }
          .signature-line { margin-top: 40px; }
          .sig-row { display: flex; margin-bottom: 15px; }
          .sig-label { width: 150px; font-weight: bold; }
          .sig-value { border-bottom: 1px solid #333; flex: 1; height: 20px; }
          .footer { margin-top: 50px; font-size: 10px; color: #777; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }
        </style>
      </head>
      <body>
        <div class="header-title">${title}</div>
        
        <div class="date">Date: ${new Date().toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })}</div>
        
        <div class="recipient">To: ${leadItem.partyName || 'Valued Partner'}</div>
        <div class="subject">Subject: ${subject}</div>
        
        <div class="greeting">Dear ${leadItem.partyName || 'Sir/Madam'},</div>
        <div class="main-text">
          This is what I ${isDebt ? 'owe to' : 'am owed by'} ${leadItem.partyName || 'you'} as of this date (${new Date().toLocaleDateString()}).
          This letter serves as a formal acknowledgment and statement of the ${isDebt ? 'debt' : 'credit'} that I, <strong>${creatorName}</strong>, 
          residing at <strong>${creatorAddress}</strong>. Tel:<strong>${creatorTel}</strong>, owes to you as of the date indicated above.
        </div>
        
        <div class="details-title">${isDebt ? 'Debt' : 'Credit'} Details:</div>
        <table>
          <thead>
            <tr>
              <th style="width: 30px;">#</th>
              <th>Reason</th>
              <th style="width: 120px;">Amount</th>
              <th>Notes</th>
            </tr>
          </thead>
          <tbody>
            ${items.map((item, idx) => `
              <tr>
                <td>${idx + 1}</td>
                <td>${item.category}</td>
                <td style="font-weight: bold;">${item.amount.toLocaleString('en-US')} ${country.currency}</td>
                <td>${item.description || '-'}</td>
              </tr>
            `).join('')}
            <tr class="total-row">
              <td colspan="2" style="text-align: right;">TOTAL</td>
              <td colspan="2">${totalAmount.toLocaleString('en-US')} ${country.currency}</td>
            </tr>
          </tbody>
        </table>
        
        <div class="amount-box">
          <div style="font-size: 14px; margin-bottom: 5px;">Total Amount ${isDebt ? 'Owed' : 'Due'}:</div>
          <div class="amount-large">${totalAmount.toLocaleString()} ${country.currency}</div>
        </div>
        
        <div class="main-text">
          I kindly request that you review this statement and confirm its accuracy. If there are any discrepancies, omissions, or additional amounts that should be included, please indicate them in the section below.
        </div>
        
        <div class="confirmation-box">
          <div class="confirmation-title">${isDebt ? 'CREDITOR' : 'DEBTOR'}'S CONFIRMATION</div>
          <div style="font-size: 13px; margin-bottom: 15px;">Please tick the appropriate box and sign below:</div>
          
          <div class="checkbox-item">
            <div class="checkbox"></div>
            <div>I confirm that the amount stated above (${totalAmount.toLocaleString('en-US')} ${country.currency}) is correct and complete.</div>
          </div>
          <div class="checkbox-item">
            <div class="checkbox"></div>
            <div>The amount stated is incorrect. The correct amount is: ____________________ ${country.currency}</div>
          </div>
          <div class="checkbox-item">
            <div class="checkbox"></div>
            <div>There are additional amounts/items not included. Details: _________________________________________________</div>
          </div>
        </div>
        
        <div class="signature-line">
          <div class="sig-row"><div class="sig-label">Signature:</div><div class="sig-value"></div></div>
          <div class="sig-row"><div class="sig-label">Date:</div><div class="sig-value"></div></div>
          <div class="sig-row"><div class="sig-label">Contact Number:</div><div class="sig-value"></div></div>
        </div>
        
        <div class="footer">
          <strong>ZAIZEN</strong> - Shari'ah Compliant Estate & Wealth Management<br/>
          Created by ${creatorName} | Email: ${creatorEmail}<br/>
          Generated via Zaizen Application
        </div>
      </body>
    </html>
  `;

  await printToFile(html, isDebt ? 'Debt_Confirmation' : 'Credit_Confirmation');
}

export async function exportWillToPDF(
  items: LedgerItem[],
  country: Country,
  result: CalculationResult,
  selectedHeirs: Heir[]
) {
  const creatorName = "GHOUENZEN SOULEMANOU";
  const creatorEmail = "gsouleman@gmail.com";
  const creatorAddress = "Douala, Cameroon";
  const creatorTel = "675 29 98 68 / 697 11 11 59";

  const html = `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
        <style>
          body { font-family: 'Times New Roman', Times, serif; padding: 50px; color: #000; line-height: 1.5; }
          .title { text-align: center; font-size: 24px; font-weight: bold; margin-bottom: 30px; text-decoration: underline; }
          .section-title { font-size: 18px; font-weight: bold; margin-top: 30px; margin-bottom: 10px; border-bottom: 1px solid #000; }
          .declaration { text-align: justify; margin-bottom: 20px; }
          table { width: 100%; border-collapse: collapse; margin-top: 10px; margin-bottom: 20px; }
          th { text-align: left; padding: 10px; border: 1px solid #ddd; background-color: #f9f9f9; }
          td { padding: 10px; border: 1px solid #ddd; }
          .footer { margin-top: 50px; font-size: 12px; border-top: 1px solid #eee; padding-top: 20px; text-align: center; }
          .sig-block { margin-top: 40px; }
          .sig-row { display: flex; justify-content: space-between; margin-bottom: 40px; }
          .sig-line { border-top: 1px solid #000; width: 200px; text-align: center; padding-top: 5px; font-size: 12px; }
        </style>
      </head>
      <body>
        <div class="title">LAST WILL AND TESTAMENT</div>
        
        <div class="declaration">
          I, <strong>${creatorName}</strong>, residing at ${creatorAddress}, being of sound mind and memory, 
          do hereby make, publish and declare this to be my Last Will and Testament, revoking all wills and codicils 
          heretofore made by me.
        </div>

        <div class="section-title">ARTICLE I: FUNERAL AND DEBTS</div>
        <div class="declaration">
          I direct that my funeral expenses and all my just debts be paid as soon after my death as may be practicable.
        </div>

        <div class="section-title">ARTICLE II: LIST OF ASSETS</div>
        <table>
          <thead><tr><th>Category</th><th>Description</th><th style="text-align: right;">Value</th></tr></thead>
          <tbody>
            ${items.filter(i => i.type === 'asset').map(i => `
              <tr><td>${i.category}</td><td>${i.description}</td><td style="text-align: right;">${i.amount.toLocaleString('en-US')} ${country.currency}</td></tr>
            `).join('')}
          </tbody>
        </table>

        <div class="section-title">ARTICLE III: LIABILITIES AND CREDITS</div>
        <p><strong>Outstanding Debts (I owe to others):</strong></p>
        <table>
          <thead><tr><th>Creditor Name</th><th>Category</th><th style="text-align: right;">Amount</th></tr></thead>
          <tbody>
            ${items.filter(i => i.type === 'debt').map(i => `
              <tr><td>${i.partyName || 'N/A'}</td><td>${i.category}</td><td style="text-align: right;">${i.amount.toLocaleString('en-US')} ${country.currency}</td></tr>
            `).join('')}
          </tbody>
        </table>

        <p><strong>Outstanding Credits (To be collected):</strong></p>
        <table>
          <thead><tr><th>Debtor Name</th><th>Category</th><th style="text-align: right;">Amount</th></tr></thead>
          <tbody>
            ${items.filter(i => i.type === 'credit').map(i => `
              <tr><td>${i.partyName || 'N/A'}</td><td>${i.category}</td><td style="text-align: right;">${i.amount.toLocaleString('en-US')} ${country.currency}</td></tr>
            `).join('')}
          </tbody>
        </table>

        <div class="section-title">ARTICLE IV: RELIGIOUS DISTRIBUTION (FARA'ID)</div>
        <div class="declaration">
          I direct that the residue of my estate, after payment of debts and wasiyyah, be distributed among my heirs according to the Islamic Law of Inheritance as follows:
        </div>
        <table>
          <thead><tr><th>Heir Type</th><th>Names</th><th style="text-align: right;">Estimated Share</th></tr></thead>
          <tbody>
            ${result.distributions.map(d => `
              <tr>
                <td>${d.heir.charAt(0).toUpperCase() + d.heir.slice(1)}</td>
                <td>${d.names && d.names.some(n => n.trim()) ? d.names.filter(n => n.trim()).join(', ') : 'N/A'}</td>
                <td style="text-align: right;">${(d.share * 100).toFixed(2)}%</td>
              </tr>
            `).join('')}
          </tbody>
        </table>

        <div class="section-title">ARTICLE V: EXECUTION</div>
        <div class="declaration">
          In witness whereof, I have hereunto set my hand this ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}.
        </div>

        <div class="sig-block">
          <div class="sig-row">
            <div class="sig-line">Testator Signature</div>
            <div class="sig-line">Date</div>
          </div>
          <div class="sig-row">
            <div class="sig-line">Witness 1 Signature</div>
            <div class="sig-line">Witness 2 Signature</div>
          </div>
        </div>

        <div class="footer">
          Generated via <strong>ZAIZEN</strong> Application<br/>
          Creator: ${creatorName} | Email: ${creatorEmail} | Tel: ${creatorTel}
        </div>
      </body>
    </html>
  `;

  await printToFile(html, 'Last_Will_and_Testament');
}

async function printToFile(html: string, fileName: string) {
  const { uri } = await Print.printToFileAsync({ html });

  if (Platform.OS === 'ios') {
    await Sharing.shareAsync(uri);
  } else {
    // Rename if possible or share directly
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle: fileName,
      UTI: 'com.adobe.pdf'
    });
  }
}
